### ISSUE TITLE
REQUEST: Support for always on TV sensor bar.

### ISSUE THREAD

**Issue by Zachruff** [WiiDatabase/DRC-Sensorbar#2]
So apparently the regular sensor bar on the TV does not receive power and turn on when there are no active Wiimotes connected to the console. Would it be possible to add a feature to keep this always on as well? I was going to use the sensor bar for dolphin by having the Wii U powering it, but I only have one Wiimote so I cant keep it powered while also having the Wiimore paired to dolphin...

**Comment by Brawl345** [comment]
Not possible and out of scope, sorry
